all:
	/opt/microblazeel-xilinx-elf/bin/microblazeel-xilinx-elf-gcc main.c -o dummy.elf \
        -I /opt/microblazeel-xilinx-elf/include -L /opt/microblazeel-xilinx-elf/lib/ \
        -L /usr/local/lib/python3.6/dist-packages/pynq/lib/rpi/bsp_iop_rpi/iop_rpi_mb/lib/
